[package]
name = "calculator"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]

[dependencies]
calculate = "0.5.1"
lazy_static = "1.2.0"
orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk.git" }